import React,{useEffect,useState} from 'react';
import { BookOpen,Plus,RefreshCw,ExternalLink,AlertTriangle,CheckCircle2,Clock } from 'lucide-react';
import { LibraryDocument,User } from '../../types'; import { SearchInput } from '../common/SearchInput'; import { Button } from '../common/Button'; import { Modal } from '../common/Modal'; import { EmptyState } from '../common/EmptyState'; import { api } from '../../services/api';
export interface LearningResourcesViewProps{currentUser:User|null;onShowToast:(type:'success'|'error'|'info',msg:string)=>void;}
const to64=(f:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result||'');resolve(s.includes(',')?s.split(',')[1]:s)};r.onerror=()=>reject(new Error('Unable to read file'));r.readAsDataURL(f)});
export const LearningResourcesView:React.FC<LearningResourcesViewProps>=({currentUser,onShowToast})=>{
 const [documents,setDocuments]=useState<LibraryDocument[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[showAdd,setShowAdd]=useState(false),[title,setTitle]=useState(''),[category,setCategory]=useState('Institutional Guideline'),[file,setFile]=useState<File|null>(null),[saving,setSaving]=useState(false),[preview,setPreview]=useState<LibraryDocument|null>(null),[syncing,setSyncing]=useState(false);
 const isAdmin=Boolean(currentUser?.isAdmin);
 const load=async()=>{setLoading(true);try{setDocuments(await api.listLibraryDocuments(search))}catch(e:any){onShowToast('error',e.message||'Failed to load library')}finally{setLoading(false)}};useEffect(()=>{const t=setTimeout(()=>void load(),200);return()=>clearTimeout(t)},[search]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();if(!file)return;setSaving(true);try{if(file.size>8*1024*1024)throw new Error('Maximum file size is 8 MB.');await api.addLibraryDocument({title:title.trim(),category,filename:file.name,mime_type:file.type||'application/octet-stream',file_size:file.size,file_base64:await to64(file)});onShowToast('success','Document uploaded. Automatic extraction/indexing status is shown below.');setShowAdd(false);setTitle('');setFile(null);await load();}catch(e:any){onShowToast('error',e.message||'Upload failed')}finally{setSaving(false)}};
 const sync=async()=>{setSyncing(true);try{const r=await api.syncDriveLibrary();onShowToast('success',`Drive Library sync: ${r.added} added, ${r.updated} updated, ${r.failed} failed.`);await load();}catch(e:any){onShowToast('error',e.message||'Drive sync failed')}finally{setSyncing(false)}};
 const retry=async(d:LibraryDocument)=>{try{await api.retryLibraryExtraction(d.id);onShowToast('info','Extraction retry completed.');await load();}catch(e:any){onShowToast('error',e.message||'Extraction retry failed')}};
 return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h2 className="text-xl font-extrabold text-slate-900 flex items-center gap-2"><BookOpen className="w-5 h-5 text-emerald-700"/>Centralized Institutional CNE Library & Guidelines</h2><p className="text-xs text-slate-500 mt-1">Original files are stored in Drive; extracted text/chunks are indexed in D1 for evidence-grounded MCQs.</p></div><div className="flex gap-2"><SearchInput value={search} onChange={setSearch} placeholder="Search guidelines..."/>{isAdmin&&<><Button variant="outline" size="sm" onClick={sync} loading={syncing} icon={<RefreshCw className="w-4 h-4"/>}>Sync Drive</Button><Button variant="primary" size="sm" onClick={()=>setShowAdd(true)} icon={<Plus className="w-4 h-4"/>}>Add Document</Button></>}</div></div>
 {loading?<div className="p-8 text-center text-xs text-slate-500">Loading library…</div>:documents.length===0?<EmptyState title="No library documents found" description="Institutional SOPs, protocols and guidelines will appear here." icon={<BookOpen className="w-10 h-10 text-slate-300"/>}/>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{documents.map(d=><div key={d.id} className="bg-white rounded-xl border p-5 flex flex-col justify-between"><div><div className="flex justify-between gap-2"><span className="text-[11px] font-semibold text-emerald-800 bg-emerald-50 px-2 py-0.5 rounded">{d.category}</span><Status status={d.extraction_status}/></div><h3 className="font-bold text-sm mt-3">{d.title}</h3><p className="text-xs text-slate-500 mt-2 line-clamp-3">{d.extracted_text||d.extraction_error||'Awaiting automatic extraction.'}</p></div><div className="mt-4 pt-3 border-t flex flex-wrap gap-2 text-xs"><button onClick={()=>setPreview(d)} className="font-semibold text-emerald-700">View Details</button>{d.file_url&&<a href={d.file_url} target="_blank" rel="noreferrer" className="font-semibold text-blue-700 inline-flex gap-1"><ExternalLink className="w-3.5 h-3.5"/>Open file</a>}{isAdmin&&d.extraction_status==='FAILED'&&<button onClick={()=>void retry(d)} className="font-semibold text-amber-700">Retry extraction</button>}</div></div>)}</div>}
 <Modal isOpen={showAdd} onClose={()=>setShowAdd(false)} title="Add Institutional Guideline" subtitle="The file will be uploaded to Drive and automatically extracted/indexed." maxWidth="lg"><form onSubmit={add} className="space-y-4"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Document title" className="w-full px-3.5 py-2 border rounded-lg text-sm"/><select value={category} onChange={e=>setCategory(e.target.value)} className="w-full px-3.5 py-2 border rounded-lg text-sm"><option>Institutional Guideline</option><option>Clinical Protocol</option><option>Infection Control SOP</option><option>Pharmacological Safety</option><option>Nursing Standard Practice</option></select><input type="file" required accept=".pdf,.doc,.docx,.ppt,.pptx,.txt" onChange={e=>setFile(e.target.files?.[0]||null)} className="w-full px-3 py-2 border rounded-lg text-xs"/><p className="text-[11px] text-slate-500">Maximum 8 MB. PDF/DOC/DOCX/PPT/PPTX extraction requires Advanced Drive service in Apps Script.</p><div className="flex justify-end gap-2"><Button type="button" variant="ghost" size="sm" onClick={()=>setShowAdd(false)}>Cancel</Button><Button type="submit" variant="primary" size="sm" loading={saving}>Upload & Index</Button></div></form></Modal>
 {preview&&<Modal isOpen onClose={()=>setPreview(null)} title={preview.title} subtitle={`${preview.category} · ${preview.extraction_status}`} maxWidth="2xl"><div className="space-y-3"><div className="p-4 bg-slate-50 border rounded-xl text-xs whitespace-pre-wrap max-h-96 overflow-auto">{preview.extracted_text||preview.extraction_error||'No extracted text is available.'}</div>{preview.file_url&&<a href={preview.file_url} target="_blank" rel="noreferrer" className="text-xs font-semibold text-blue-700">Open original Drive file</a>}</div></Modal>}
 </div>;
};
const Status:React.FC<{status:string}>=({status})=>status==='INDEXED'?<span className="text-[10px] text-emerald-700 inline-flex gap-1"><CheckCircle2 className="w-3 h-3"/>Indexed</span>:status==='FAILED'?<span className="text-[10px] text-red-700 inline-flex gap-1"><AlertTriangle className="w-3 h-3"/>Failed</span>:<span className="text-[10px] text-amber-700 inline-flex gap-1"><Clock className="w-3 h-3"/>Pending</span>;
