import React,{useEffect,useState} from 'react';
import { Globe,Award,BookOpen,FileText,ExternalLink,Image as ImageIcon,Activity,Plus,Trash2,Edit2,Eye,EyeOff,ChevronUp,ChevronDown } from 'lucide-react';
import { Button } from '../common/Button'; import { Modal } from '../common/Modal'; import { api } from '../../services/api';
export interface AdminContentProps{onShowToast:(type:'success'|'error'|'info',msg:string)=>void;}
const file64=(f:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result||'');resolve(s.includes(',')?s.split(',')[1]:s)};r.onerror=()=>reject(new Error('Unable to read file'));r.readAsDataURL(f)});
const bool=(v:any)=>v===true||v===1;
export const AdminContent:React.FC<AdminContentProps>=({onShowToast})=>{
 const [content,setContent]=useState<any>({news:[],quick_links:[],gallery:[],institutional:[]}),[loading,setLoading]=useState(true);
 const [chair,setChair]=useState<any>({name:'',designation:'',message:'',is_published:true}),[chairFile,setChairFile]=useState<File|null>(null),[coord,setCoord]=useState<any>({name:'',title:'',message:'',is_published:true});
 const [modal,setModal]=useState<'news'|'link'|'gallery'|null>(null),[draft,setDraft]=useState<any>({}),[galleryFile,setGalleryFile]=useState<File|null>(null),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const x=await api.getAdminContent();setContent(x);if(x.chairperson)setChair({...x.chairperson,is_published:bool(x.chairperson.is_published)});if(x.coordinator)setCoord({...x.coordinator,is_published:bool(x.coordinator.is_published)});}catch(e:any){onShowToast('error',e.message||'Failed to load portal content');}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const saveChair=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const payload:any={name:chair.name,designation:chair.designation,message:chair.message,is_published:chair.is_published};if(chairFile){payload.photo_file_base64=await file64(chairFile);payload.photo_filename=chairFile.name;payload.photo_mime_type=chairFile.type;}await api.updateChairperson(payload);onShowToast('success','Chairperson content saved.');setChairFile(null);await load();}catch(e:any){onShowToast('error',e.message);}finally{setSaving(false)}};
 const saveCoord=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{await api.updateCoordinator(coord);onShowToast('success','Coordinator content saved.');await load();}catch(e:any){onShowToast('error',e.message);}finally{setSaving(false)}};
 const create=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{if(modal==='news')await api.createNews({...draft,is_published:true,display_order:(content.news?.length||0)+1});if(modal==='link')await api.createQuickLink({...draft,is_active:true,display_order:(content.quick_links?.length||0)+1});if(modal==='gallery'){if(!galleryFile)throw new Error('Select an image file.');if(galleryFile.size>8*1024*1024)throw new Error('Image must not exceed 8 MB.');await api.createGalleryItem({...draft,image_file_base64:await file64(galleryFile),image_filename:galleryFile.name,image_mime_type:galleryFile.type,is_published:true,display_order:(content.gallery?.length||0)+1});}onShowToast('success','Portal content added.');setModal(null);setDraft({});setGalleryFile(null);await load();}catch(e:any){onShowToast('error',e.message||'Unable to save content');}finally{setSaving(false)}};
 const editNews=async(n:any)=>{const title=prompt('News title',n.title);if(title===null)return;const body=prompt('News/circular text',n.content);if(body===null)return;await api.updateNews(n.id,{title,content:body});await load();};
 const editLink=async(l:any)=>{const title=prompt('Link title',l.title);if(title===null)return;const url=prompt('URL',l.url);if(url===null)return;await api.updateQuickLink(l.id,{title,url});await load();};
 const editGallery=async(g:any)=>{const title=prompt('Gallery title',g.title);if(title===null)return;const caption=prompt('Caption',g.caption||'');if(caption===null)return;await api.updateGalleryItem(g.id,{title,caption});await load();};
 const shift=async(kind:'news'|'link'|'gallery',item:any,delta:number)=>{const order=Math.max(1,Number(item.display_order||1)+delta);if(kind==='news')await api.updateNews(item.id,{display_order:order});if(kind==='link')await api.updateQuickLink(item.id,{display_order:order});if(kind==='gallery')await api.updateGalleryItem(item.id,{display_order:order});await load();};
 if(loading)return <div className="p-8 text-sm text-slate-500">Loading institutional content…</div>;
 return <div className="space-y-8"><div><h2 className="text-xl font-extrabold text-slate-900 flex items-center gap-2"><Globe className="w-5 h-5 text-emerald-700"/>Institutional Content & Portal CMS</h2><p className="text-xs text-slate-500 mt-1">Manage published Home content. Leadership/gallery images are stored in Google Drive.</p></div>
 <div className="grid lg:grid-cols-2 gap-6"><form onSubmit={saveChair} className="bg-white rounded-xl border p-5 space-y-3"><h3 className="text-sm font-bold flex items-center gap-2"><Award className="w-4 h-4 text-emerald-700"/>Chairperson</h3><input required value={chair.name||''} onChange={e=>setChair({...chair,name:e.target.value})} placeholder="Name" className="w-full px-3 py-2 border rounded text-xs"/><input required value={chair.designation||''} onChange={e=>setChair({...chair,designation:e.target.value})} placeholder="Designation" className="w-full px-3 py-2 border rounded text-xs"/><textarea required rows={4} value={chair.message||''} onChange={e=>setChair({...chair,message:e.target.value})} placeholder="Message" className="w-full px-3 py-2 border rounded text-xs"/><input type="file" accept="image/*" onChange={e=>setChairFile(e.target.files?.[0]||null)} className="w-full text-xs"/>{chair.photo_url&&<img src={chair.photo_url} alt="Current Chairperson" className="w-20 h-20 object-cover rounded-lg border"/>}<label className="text-xs flex gap-2"><input type="checkbox" checked={chair.is_published!==false} onChange={e=>setChair({...chair,is_published:e.target.checked})}/>Published</label><Button type="submit" variant="primary" size="sm" loading={saving}>Save Chairperson</Button></form>
 <form onSubmit={saveCoord} className="bg-white rounded-xl border p-5 space-y-3"><h3 className="text-sm font-bold flex items-center gap-2"><BookOpen className="w-4 h-4 text-emerald-700"/>Coordinator's Desk</h3><input required value={coord.name||''} onChange={e=>setCoord({...coord,name:e.target.value})} placeholder="Name" className="w-full px-3 py-2 border rounded text-xs"/><input required value={coord.title||''} onChange={e=>setCoord({...coord,title:e.target.value})} placeholder="Title" className="w-full px-3 py-2 border rounded text-xs"/><textarea required rows={5} value={coord.message||''} onChange={e=>setCoord({...coord,message:e.target.value})} placeholder="Message" className="w-full px-3 py-2 border rounded text-xs"/><label className="text-xs flex gap-2"><input type="checkbox" checked={coord.is_published!==false} onChange={e=>setCoord({...coord,is_published:e.target.checked})}/>Published</label><Button type="submit" variant="primary" size="sm" loading={saving}>Save Coordinator</Button></form></div>
 <Section title="News & Circulars" icon={<FileText className="w-4 h-4"/>} onAdd={()=>{setDraft({publication_date:new Date().toISOString().slice(0,10)});setModal('news')}}>{(content.news||[]).map((n:any)=><Row key={n.id} title={n.title} sub={`${n.publication_date} · ${bool(n.is_published)?'Published':'Hidden'}`} onEdit={()=>void editNews(n)} onToggle={()=>void api.updateNews(n.id,{is_published:!bool(n.is_published)}).then(load)} onUp={()=>void shift('news',n,-1)} onDown={()=>void shift('news',n,1)} onDelete={()=>void api.deleteNews(n.id).then(load)}/>)}</Section>
 <Section title="Quick Links" icon={<ExternalLink className="w-4 h-4"/>} onAdd={()=>{setDraft({});setModal('link')}}>{(content.quick_links||[]).map((l:any)=><Row key={l.id} title={l.title} sub={`${l.url} · ${bool(l.is_active)?'Active':'Inactive'}`} onEdit={()=>void editLink(l)} onToggle={()=>void api.updateQuickLink(l.id,{is_active:!bool(l.is_active)}).then(load)} onUp={()=>void shift('link',l,-1)} onDown={()=>void shift('link',l,1)} onDelete={()=>void api.deleteQuickLink(l.id).then(load)}/>)}</Section>
 <Section title="Gallery" icon={<ImageIcon className="w-4 h-4"/>} onAdd={()=>{setDraft({});setModal('gallery')}}>{(content.gallery||[]).map((g:any)=><Row key={g.id} title={g.title} sub={`${bool(g.is_published)?'Published':'Hidden'} · Drive-backed image`} image={g.image_url} onEdit={()=>void editGallery(g)} onToggle={()=>void api.updateGalleryItem(g.id,{is_published:!bool(g.is_published)}).then(load)} onUp={()=>void shift('gallery',g,-1)} onDown={()=>void shift('gallery',g,1)} onDelete={()=>void api.deleteGalleryItem(g.id).then(load)}/>)}</Section>
 <Section title="Institutional Impact" icon={<Activity className="w-4 h-4"/>}>{(content.institutional||[]).map((m:any)=><div key={m.key} className="flex gap-3 items-center border-b py-2"><div className="flex-1 text-xs"><b>{m.label}</b><div className="text-slate-400">{m.description}</div></div><input defaultValue={m.value} onBlur={e=>{if(e.target.value!==m.value)void api.updateInstitutionalMetric(m.key,e.target.value).then(load)}} className="w-32 px-2 py-1 border rounded text-xs"/></div>)}</Section>
 <Modal isOpen={!!modal} onClose={()=>setModal(null)} title={modal==='news'?'Add News / Circular':modal==='link'?'Add Quick Link':'Add Gallery Image'} maxWidth="lg"><form onSubmit={create} className="space-y-3"><input required placeholder="Title" value={draft.title||''} onChange={e=>setDraft({...draft,title:e.target.value})} className="w-full px-3 py-2 border rounded text-sm"/>{modal==='news'&&<><textarea required placeholder="Content" value={draft.content||''} onChange={e=>setDraft({...draft,content:e.target.value})} className="w-full px-3 py-2 border rounded text-sm"/><input type="date" required value={draft.publication_date||''} onChange={e=>setDraft({...draft,publication_date:e.target.value})} className="w-full px-3 py-2 border rounded text-sm"/><input type="url" placeholder="Optional circular link" value={draft.file_url||''} onChange={e=>setDraft({...draft,file_url:e.target.value})} className="w-full px-3 py-2 border rounded text-sm"/></>}{modal==='link'&&<input type="url" required placeholder="https://..." value={draft.url||''} onChange={e=>setDraft({...draft,url:e.target.value})} className="w-full px-3 py-2 border rounded text-sm"/>}{modal==='gallery'&&<><textarea placeholder="Caption" value={draft.caption||''} onChange={e=>setDraft({...draft,caption:e.target.value})} className="w-full px-3 py-2 border rounded text-sm"/><input type="file" required accept="image/*" onChange={e=>setGalleryFile(e.target.files?.[0]||null)} className="w-full text-xs"/></>}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" size="sm" onClick={()=>setModal(null)}>Cancel</Button><Button type="submit" variant="primary" size="sm" loading={saving}>Save</Button></div></form></Modal>
 </div>;
};
const Section:React.FC<{title:string;icon:React.ReactNode;onAdd?:()=>void;children:React.ReactNode}>=({title,icon,onAdd,children})=><div className="bg-white rounded-xl border p-5"><div className="flex items-center justify-between mb-3"><h3 className="text-sm font-bold flex items-center gap-2">{icon}{title}</h3>{onAdd&&<Button variant="outline" size="sm" onClick={onAdd} icon={<Plus className="w-3.5 h-3.5"/>}>Add</Button>}</div><div>{children}</div></div>;
const Row:React.FC<{title:string;sub?:string;image?:string;onEdit:()=>void;onToggle:()=>void;onUp:()=>void;onDown:()=>void;onDelete:()=>void}>=({title,sub,image,onEdit,onToggle,onUp,onDown,onDelete})=><div className="flex items-center gap-3 py-2 border-b last:border-0">{image&&<img src={image} alt="" className="w-12 h-10 object-cover rounded border"/>}<div className="flex-1 min-w-0"><div className="text-xs font-semibold truncate">{title}</div><div className="text-[10px] text-slate-400 truncate">{sub}</div></div><button onClick={onEdit} title="Edit"><Edit2 className="w-3.5 h-3.5"/></button><button onClick={onToggle} title="Toggle visibility"><Eye className="w-3.5 h-3.5"/></button><button onClick={onUp} title="Move up"><ChevronUp className="w-3.5 h-3.5"/></button><button onClick={onDown} title="Move down"><ChevronDown className="w-3.5 h-3.5"/></button><button onClick={onDelete} title="Delete" className="text-red-600"><Trash2 className="w-3.5 h-3.5"/></button></div>;
