import React,{useEffect,useState} from 'react';
import { Activity,Database,Cloud,Sparkles,RefreshCw,CheckCircle2,AlertTriangle,BookOpen } from 'lucide-react';
import { Button } from '../common/Button'; import { api } from '../../services/api'; import { AdminDiagnosticsData } from '../../types';
export interface AdminDiagnosticsProps{onShowToast:(type:'success'|'error'|'info',msg:string)=>void;}
export const AdminDiagnostics:React.FC<AdminDiagnosticsProps>=({onShowToast})=>{
 const [diag,setDiag]=useState<AdminDiagnosticsData|null>(null),[loading,setLoading]=useState(true),[processing,setProcessing]=useState(false),[testing,setTesting]=useState(false),[result,setResult]=useState<any>(null);
 const load=async()=>{setLoading(true);try{setDiag(await api.getSystemDiagnostics())}catch(e:any){onShowToast('error',e.message||'Failed to load diagnostics')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const backup=async()=>{setProcessing(true);try{const r:any=await api.triggerBackupQueueProcess();onShowToast('success',`Backup processing finished: ${r.processed||0} processed.`);await load()}catch(e:any){onShowToast('error',e.message||'Backup processing failed')}finally{setProcessing(false)}};
 const test=async()=>{setTesting(true);setResult(null);try{const r=await api.testGemini();setResult(r);onShowToast('success','Gemini connectivity test succeeded.')}catch(e:any){onShowToast('error',e.message||'Gemini test failed')}finally{setTesting(false)}};
 const healthy=diag?.database?.status==='OK'; const model=diag?.ai_service?.model_name||'Not configured';
 if(loading&&!diag)return <div className="p-8 text-xs text-slate-500">Loading diagnostics…</div>;
 return <div className="space-y-6"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-extrabold text-slate-900 flex items-center gap-2"><Activity className="w-5 h-5 text-emerald-700"/>System Infrastructure & Integration Diagnostics</h2><p className="text-xs text-slate-500 mt-1">Live configuration and D1 health information. Secret values are never displayed.</p></div><Button variant="outline" size="sm" onClick={load} icon={<RefreshCw className="w-4 h-4"/>}>Refresh</Button></div>
 <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-5">
 <Card title="Cloudflare D1" icon={<Database className="w-5 h-5"/>} ok={healthy}><Line a="Status" b={diag?.database?.status||'UNKNOWN'}/><Line a="Tables" b={String(diag?.database?.tables_count??0)}/><Line a="Employees / CNEs" b={`${diag?.database?.employees_total??0} / ${diag?.database?.cnes_total??0}`}/>{diag?.database?.error&&<div className="text-[10px] text-red-600">{diag.database.error}</div>}</Card>
 <Card title="Google Integration" icon={<Cloud className="w-5 h-5"/>} ok={Boolean(diag?.google_integration?.configured)}><Line a="Configured" b={diag?.google_integration?.configured?'Yes':'No'}/><Line a="Pending backup" b={String(diag?.backup_queue?.total_pending??0)}/><Line a="Retryable failures" b={String(diag?.backup_queue?.failed_retryable??0)}/><Button variant="outline" size="sm" loading={processing} onClick={backup} className="w-full justify-center">Process Queue</Button></Card>
 <Card title="Gemini" icon={<Sparkles className="w-5 h-5"/>} ok={Boolean(diag?.ai_service?.configured)}><Line a="Configured" b={diag?.ai_service?.configured?'Yes':'No'}/><Line a="Model" b={model}/><Line a="Generation rule" b={diag?.ai_service?.generation_rule||'—'}/><Button variant="primary" size="sm" loading={testing} onClick={test} className="w-full justify-center">Test Gemini</Button></Card>
 <Card title="CNE Library" icon={<BookOpen className="w-5 h-5"/>} ok={(diag?.institutional_library?.extraction_failed??0)===0}><Line a="Active documents" b={String(diag?.institutional_library?.active_documents??0)}/><Line a="Indexed chunks" b={String(diag?.institutional_library?.indexed_chunks??0)}/><Line a="Extraction pending" b={String(diag?.institutional_library?.extraction_pending??0)}/><Line a="Extraction failed" b={String(diag?.institutional_library?.extraction_failed??0)}/></Card>
 </div>{result&&<pre className="p-4 bg-slate-900 text-emerald-200 rounded-xl text-xs overflow-auto">{JSON.stringify(result,null,2)}</pre>}</div>;
};
const Card:React.FC<{title:string;icon:React.ReactNode;ok:boolean;children:React.ReactNode}>=({title,icon,ok,children})=><div className="bg-white rounded-xl border p-5 space-y-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-bold">{icon}{title}</div>{ok?<CheckCircle2 className="w-4 h-4 text-emerald-600"/>:<AlertTriangle className="w-4 h-4 text-amber-600"/>}</div><div className="space-y-2 text-xs border-t pt-3">{children}</div></div>;
const Line:React.FC<{a:string;b:string}>=({a,b})=><div className="flex justify-between gap-3"><span className="text-slate-500">{a}</span><strong className="text-slate-800 text-right break-all">{b}</strong></div>;
