import React,{useEffect,useMemo,useState} from 'react';
import { ClipboardList, CheckCircle2, XCircle, ChevronLeft, ChevronRight } from 'lucide-react';
import { CneApplication, Area } from '../../types';
import { Badge } from '../common/Badge'; import { Button } from '../common/Button'; import { SearchInput } from '../common/SearchInput'; import { Select } from '../common/Select'; import { EmptyState } from '../common/EmptyState'; import { api } from '../../services/api';
export interface ApplicationManagementProps{areas:Area[];onShowToast:(type:'success'|'error'|'info',msg:string)=>void;}
export const ApplicationManagement:React.FC<ApplicationManagementProps>=({areas,onShowToast})=>{
 const [applications,setApplications]=useState<CneApplication[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[status,setStatus]=useState('Pending'),[area,setArea]=useState(''),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0); const pageSize=20;
 useEffect(()=>{setPage(1)},[search,status,area,dateFrom,dateTo]);
 useEffect(()=>{const t=setTimeout(()=>void load(),250);return()=>clearTimeout(t);},[search,status,area,dateFrom,dateTo,page]);
 const load=async()=>{setLoading(true);try{const res=await api.listApplications({search,status,area,date_from:dateFrom,date_to:dateTo,page:String(page),page_size:String(pageSize)});setApplications(res.items||[]);setTotal(res.total||0);}catch(err:any){onShowToast('error',err.message||'Failed to load applications');}finally{setLoading(false);}};
 const pages=Math.max(1,Math.ceil(total/pageSize));
 const review=async(id:string,decision:'Approved'|'Rejected')=>{const notes=window.prompt(`${decision} application — optional reviewer note:`,'') ?? undefined;try{await api.reviewApplication(id,decision,notes);onShowToast('success',`Application marked ${decision}.`);await load();}catch(err:any){onShowToast('error',err.message||'Review failed');}};
 return <div className="space-y-6"><div><h2 className="text-xl font-extrabold text-slate-900 tracking-tight flex items-center gap-2"><ClipboardList className="w-5 h-5 text-emerald-700"/>CNE Enrollment Applications Review</h2><p className="text-xs text-slate-500 mt-1">Server-filtered institutional registration review with capacity-safe approval.</p></div>
 <div className="bg-white p-4 rounded-xl border border-slate-200/90 shadow-2xs grid grid-cols-1 md:grid-cols-5 gap-3"><SearchInput value={search} onChange={setSearch} placeholder="Officer, ID or CNE..."/><Select options={[{value:'Pending',label:'Pending Review'},{value:'Approved',label:'Approved'},{value:'Rejected',label:'Rejected'},{value:'',label:'All Statuses'}]} value={status} onChange={e=>setStatus(e.target.value)}/><Select options={areas.map(a=>({value:a.id,label:`${a.name} (${a.code})`}))} value={area} onChange={e=>setArea(e.target.value)} placeholder="All Clinical Areas"/><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="px-3 py-2 border rounded-lg text-xs" aria-label="From date"/><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} className="px-3 py-2 border rounded-lg text-xs" aria-label="To date"/></div>
 {loading?<div className="p-8 text-center text-xs text-slate-500">Loading applications…</div>:applications.length===0?<EmptyState title="No applications found" description="No applications match the selected criteria." icon={<ClipboardList className="w-10 h-10 text-slate-300"/>}/>:<div className="bg-white rounded-xl border border-slate-200/90 shadow-2xs overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 border-b text-slate-600 uppercase text-[11px]"><tr><th className="p-3.5">Applicant</th><th className="p-3.5">CNE</th><th className="p-3.5">Date & Area</th><th className="p-3.5">Status</th><th className="p-3.5 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{applications.map(app=><tr key={app.id}><td className="p-3.5"><div className="font-bold">{app.employee_name||app.employee_id}</div><div className="font-mono text-[11px] text-slate-400">{app.employee_id}</div></td><td className="p-3.5"><div className="font-semibold">{app.cne_title}</div><div className="text-[11px] text-slate-400">{(app as any).cne_code||''} · {app.venue}</div></td><td className="p-3.5"><div>{app.cne_date}</div><div className="text-[11px] text-teal-800">{app.area_name}</div></td><td className="p-3.5"><Badge status={app.status} size="sm"/></td><td className="p-3.5 text-right">{app.status==='Pending'?<div className="flex justify-end gap-2"><Button variant="primary" size="sm" onClick={()=>review(app.id,'Approved')} icon={<CheckCircle2 className="w-3.5 h-3.5"/>}>Approve</Button><Button variant="destructive" size="sm" onClick={()=>review(app.id,'Rejected')} icon={<XCircle className="w-3.5 h-3.5"/>}>Reject</Button></div>:<span className="text-slate-400">Reviewed</span>}</td></tr>)}</tbody></table></div><div className="p-3 border-t flex items-center justify-between text-xs"><span className="text-slate-500">{total} application{total===1?'':'s'} · Page {page} of {pages}</span><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page<=1} icon={<ChevronLeft className="w-3.5 h-3.5"/>}>Previous</Button><Button variant="outline" size="sm" onClick={()=>setPage(p=>Math.min(pages,p+1))} disabled={page>=pages}>Next <ChevronRight className="w-3.5 h-3.5 ml-1"/></Button></div></div></div>}
 </div>;
};
