import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const checks=[]; const check=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const worker=read('worker/index.ts'), migration=read('migrations/0001_initial_schema.sql'), api=read('src/services/api.ts'), apps=read('google-apps-script/Code.gs'), pkg=JSON.parse(read('package.json'));
const allProd=[...walk('worker'),...walk('src')].filter(f=>/\.(ts|tsx)$/.test(f)).map(read).join('\n');
function walk(dir){return fs.readdirSync(path.join(root,dir),{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);}
check('Worker serves static assets',worker.includes('env.ASSETS.fetch'));
check('D1 is Worker binding',read('worker/types.ts').includes('DB: D1Database'));
check('No browser localStorage auth',!allProd.includes('cne_auth_token')&&!read('src/services/api.ts').includes('localStorage'));
check('No process.env in Worker',!walk('worker').map(read).join('\n').includes('process.env'));
check('HttpOnly cookie architecture',read('worker/routes/auth.ts').includes('HttpOnly'));
check('PBKDF2 password hashing',read('worker/utils/crypto.ts').includes('PBKDF2'));
check('Rate limit table',migration.includes('auth_rate_limits'));
check('Area In-Charge table',migration.includes('area_incharge_assignments'));
check('Resource source chunks',migration.includes('resource_id TEXT REFERENCES cne_resources'));
check('Capacity trigger',migration.includes('trg_cne_participant_capacity'));
check('CNE sequence table',migration.includes('cne_sequences'));
check('Three roles seeded',migration.includes("'ADMIN'")&&migration.includes("'AREA_INCHARGE'")&&migration.includes("'EMPLOYEE'"));
check('Automatic resource extraction route',api.includes('retryCneResourceExtraction')&&read('worker/services/resourceService.ts').includes("'extract_text'"));
check('Drive Library sync',api.includes('syncDriveLibrary')&&apps.includes("action === 'list_library_files'"));
check('Apps Script extraction',apps.includes("action === 'extract_text'")&&apps.includes('Drive.Files.create'));
check('Officers header mapping',apps.includes('findHeaderIndex'));
check('Sheets fail closed',apps.includes("getRequiredProperty('BACKUP_SPREADSHEET_ID')"));
check('Officers sheet fail closed',apps.includes("getRequiredProperty('OFFICERS_SPREADSHEET_ID')"));
check('Real QR dependency',pkg.dependencies?.['qrcode.react']&&read('src/components/cne/QrAttendanceModal.tsx').includes('QRCodeSVG'));
check('QR one-tap URL handling',read('src/App.tsx').includes('attendance_token'));
check('CMS Drive images',read('worker/services/adminMasterService.ts').includes('uploadCmsImage')&&read('src/components/admin/AdminContent.tsx').includes('photo_file_base64'));
check('Security headers',read('worker/middleware/security.ts').includes('Content-Security-Policy')&&read('worker/middleware/security.ts').includes('X-Content-Type-Options'));
check('Gemini explicit default',read('wrangler.toml').includes('gemini-3.8-flash'));
check('No old Gemini branding',!allProd.includes('Gemini 2.5 Flash'));
check('No hardcoded demo credentials in prod source',!allProd.includes('Admin@123')&&!allProd.includes('CnePass@2026'));
check('Scheduled backup retry',read('wrangler.toml').includes('crons')&&worker.includes('scheduled('));
check('Application server pagination',read('worker/services/applicationService.ts').includes('LIMIT ? OFFSET ?'));
check('Calendar month range API',read('src/components/cne/CneCalendar.tsx').includes('start_date')&&read('src/components/cne/CneCalendar.tsx').includes('end_date'));
check('AI generation state lock',read('worker/services/aiMcqService.ts').includes("status = 'IN_PROGRESS'")&&read('worker/services/aiMcqService.ts').includes('meta?.changes'));
check('Post-test batch persistence',read('worker/services/postTestService.ts').includes('db.batch'));
check('Google backup uses success boolean',read('worker/services/backupService.ts').includes('success'));
const failed=checks.filter(c=>!c.ok); for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}`); console.log(`\n${checks.length-failed.length}/${checks.length} checks passed.`); if(failed.length) process.exit(1);
